name: Build Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package plugin
        id: package
        run: |
          mkdir openrouter
          mv LICENSE README.md hook.php openrouter.xml setup.php src templates openrouter/
          ARCHIVE_NAME="openrouter-${{ github.sha }}.tar.gz"
          tar -czf $ARCHIVE_NAME openrouter/
          echo "archive_name=$ARCHIVE_NAME" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openrouter-plugin
          path: ${{ steps.package.outputs.archive_name }}
